Greek translation update 20/2/2018
OpenPLi/enigma2 pull request #1288
Opened 2018-02-20 00:12 UTC by MCelliotG

Greek translation update 20/2/2018

2018-02-20 10:49 UTC, nautilus7 requested changes
I made 2 minor suggestions on this updated version. Otherwise everything looks OK!

2018-02-20 10:49 UTC, nautilus7 commented on po/el.po
> +"Θέλετε σίγουρα να συνεχίσετε; "
There is an extra space at the end.

2018-02-20 10:49 UTC, nautilus7 commented on po/el.po
> +msgstr[1] "Η ανίχνευση ολοκληρώθηκε, βρέθηκαν %d κανάλια"
Consider adding a full stop at the end in these 2 strings.

2018-02-21 02:05 UTC, MCelliotG commented on po/el.po
> +msgstr[1] "Η ανίχνευση ολοκληρώθηκε, βρέθηκαν %d κανάλια"
Thank you, I've seen these already, but I had commited my pull, so they will be visible in the next pull request. These are new strings that changed recently, the auto suggest ignored some. Some strings are missing though from the new pot, like Press OK to start the scan. I don't know what happened and they are gone!

2018-02-21 12:10 UTC, nautilus7 commented on po/el.po
> +msgstr[1] "Η ανίχνευση ολοκληρώθηκε, βρέθηκαν %d κανάλια"
Don't you use git? If you did you could easily change you pull request by amending last commit. Anyway, they are not big issues. They can be fixed in the next revision of the translation.

That specific string you mention that is gone, is indeed gone! I changed it in the code and made it identical to another one, so 1 less string to translate. See commit https://github.com/OpenPLi/enigma2/commit/ed09d8025584a898fb42870d9f1f21bf4c380ddf

2018-02-21 22:03 UTC, nautilus7 commented
This PR can now be closed. An updated version is already merged.

2018-02-21 22:54 UTC, closed without merging

2018-02-21 22:55 UTC, MCelliotG commented
Definitely right, thank you to everyone!