[Skin.py] more code refinements and enhancements
OpenPLi/enigma2 pull request #2400
Opened 2019-12-29 11:21 UTC by IanSav

- [skin.py] Change skin load order
  This change makes the skin load order match the description comment describing the skin load order.

- [skin.py] Use more appropriate variable name
  This change makes use of a consistent, reused and more appropriate variable name for processing the tags in skins.

- [skin.py] Optimise and enhance skinLoad() method
  - Extract the common code adding screens to domScreens into a single method. This eliminates a nest of "if" blocks.
  - This change also enhances the skinLoad() method to allow skin include files to add core skin elements like fonts, colours parameters, etc.

  **NOTE: If this enhanced skinLoad() feature is to be used the include files MUST be included such that the core elements are defined BEFORE they are used. That means that the order of the include files is important.**

2019-12-29 11:42 UTC, nautilus7 requested changes
This reverts the changes done in https://github.com/OpenPLi/enigma2/commit/ed1572121bc17a34f8a211f1b6809d4200539e49

2019-12-29 11:57 UTC, IanSav commented
I will be using those code enhancements to submit another update.  Mike only gave a few sample optimisations to show me how to improve the code.  I need to apply the changes in more places.

2019-12-29 11:58 UTC, IanSav commented
> This reverts the changes done in [ed15721](https://github.com/OpenPLi/enigma2/commit/ed1572121bc17a34f8a211f1b6809d4200539e49)

I will be using those code enhancements to submit another update. Mike only gave a few sample optimisations to show me how to improve the code. I need to apply the changes in more places.

2019-12-29 12:04 UTC, nautilus7 commented
Ok, I see.

Btw, the emergency skin does not load.
https://github.com/OpenPLi/enigma2/blob/bba6339a8daefac270de33b139288d049ade8cfe/skin.py#L18

It should be without the first "/" in the path or without the path, just "skin.xml".

2019-12-29 12:47 UTC, IanSav commented
> Btw, the emergency skin does not load.

Can you please give me a log file on the forum.

I am just about to commit the optimisations but I will hold off until I check your logs in case a fix is required.

2019-12-29 13:23 UTC, nautilus7 commented
> > Btw, the emergency skin does not load.
> 
> Can you please give me a log file on the forum.
> 
> I am just about to commit the optimisations but I will hold off until I check your logs in case a fix is required.

I experienced a problem yesterday, where my skin_user_myskinname.xml was not loading, and I found that by changing the emergencey skin path, it worked.

I cannot reproduce the problem t the moment, so go on with your changes. If I can make a log showing the problem, I will inform you.

2019-12-29 14:27 UTC, IanSav commented
> I experienced a problem yesterday, where my skin_user_myskinname.xml was not loading, and I found that by changing the emergency skin path, it works.
> 
> I cannot reproduce the problem at the moment, so go on with your changes. If I can make a log showing the problem, I will inform you.

I would very much like to see any logs of this issue.  The two skins should be totally unrelated but you may have found something that might need attention.

Please don't hesitate to contact me if anything doesn't look right.  Just give me the logs and I will immediately investigate.

2019-12-29 18:13 UTC, 68foxboris commented
There are no problems on the default. I install skins and enigma does not start.
skin1
`[Skin] ERROR loading file 'skin_user.xml': [Errno 2] No such file or directory: 'skin_user.xml'
[Skin] ERROR loading file 'skin_box.xml': [Errno 2] No such file or directory: 'skin_box.xml'
[Skin] ERROR loading file 'skin_second_infobar.xml': [Errno 2] No such file or directory: 'skin_second_infobar.xml'
[Skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_display.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/BlackMoonFHD/skin.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_default.xml' added successfully.
[FONT] adding font /usr/share/fonts/nmsbd.ttf -> Regular
[FONT] adding font /usr/share/fonts/andale.ttf -> Fixed
[FONT] adding font /usr/share/fonts/tuxtxt.ttf -> Console
[FONT] adding font /usr/share/fonts/DejaVuSans.ttf -> DejaVuSans
[FONT] adding font /usr/share/fonts/ae_AlMateen.ttf -> Replacement
[Skin] Loading included file '/usr/share/enigma2/BlackMoonFHD/skin_menu.xml'.
[Skin] Warning: Screen 'Buttons_sdreamng' already defined!  Using first definition.
[Skin] Warning: Screen 'Menu_sdngtit' already defined!  Using first definition.
[Skin] Warning: Screen 'Menu_sdok' already defined!  Using first definition.
[Skin] Warning: Screen 'Menu_sdngkb' already defined!  Using first definition.
[FONT] adding font BlackMoonFHD/fonts/regular.ttf[FONT] failed: No such file or directory
Killed
`
skin2
`[Skin] ERROR loading file 'skin_user.xml': [Errno 2] No such file or directory: 'skin_user.xml'
[Skin] ERROR loading file 'skin_box.xml': [Errno 2] No such file or directory: 'skin_box.xml'
[Skin] ERROR loading file 'skin_second_infobar.xml': [Errno 2] No such file or directory: 'skin_second_infobar.xml'
[Skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_display.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/HDLine-Orange/skin.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_default.xml' added successfully.
[FONT] adding font /usr/share/fonts/nmsbd.ttf -> Regular
[FONT] adding font /usr/share/fonts/andale.ttf -> Fixed
[FONT] adding font /usr/share/fonts/tuxtxt.ttf -> Console
[FONT] adding font /usr/share/fonts/DejaVuSans.ttf -> DejaVuSans
[FONT] adding font /usr/share/fonts/ae_AlMateen.ttf -> Replacement
[Skin] Loading included file '/usr/share/enigma2/HDLine-Orange/skin_menu.xml'.
[FONT] adding font HDLine-Orange/fonts/ks.ttf[FONT] failed: No such file or directory
Killed
`

2019-12-29 18:22 UTC, athoik commented
@IanSav, problem that @nautilus7  is mentioning happens due to loading of Emergency skin.

https://github.com/OpenPLi/enigma2/blob/develop/skin.py#L155

We should only load emergency skin only when we failed to load default one.


```
[SKIN] addSkin: skin_user_Satdreamgr-HD-TranspBA.xml scope 12
[Skin] Skin '/etc/enigma2/skin_user_Satdreamgr-HD-TranspBA.xml' added successfully.
[SKIN] addSkin: skin_box.xml scope 12
[Skin] ERROR loading file 'skin_box.xml': [Errno 2] No such file or directory: 'skin_box.xml'
[SKIN] addSkin: skin_second_infobar.xml scope 12
[Skin] ERROR loading file 'skin_second_infobar.xml': [Errno 2] No such file or directory: 'skin_second_infobar.xml'
[SKIN] addSkin: skin_subtitles.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
[SKIN] addSkin: skin_display.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_display.xml' added successfully.
[SKIN] addSkin: Satdreamgr-HD-TranspBA/skin.xml scope 12
[Skin] Skin '/usr/share/enigma2/Satdreamgr-HD-TranspBA/skin.xml' added successfully.
[SKIN] addSkin: /usr/share/enigma2/skin.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin.xml' added successfully.
[SKIN] addSkin: skin_default.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_default.xml' added successfully.
```

The emergency skin is loaded resulting in:

![1_0_1_28_2_212C_EEEE0000_0_0_0_20191229201439](https://user-images.githubusercontent.com/2682247/71560886-04037900-2a78-11ea-97d5-27bd1668fb6d.jpg)

Here is without emergency.

```
[SKIN] addSkin: skin_user_Satdreamgr-HD-TranspBA.xml scope 12
[Skin] Skin '/etc/enigma2/skin_user_Satdreamgr-HD-TranspBA.xml' added successfully.
[SKIN] addSkin: skin_box.xml scope 12
[Skin] ERROR loading file 'skin_box.xml': [Errno 2] No such file or directory: 'skin_box.xml'
[SKIN] addSkin: skin_second_infobar.xml scope 12
[Skin] ERROR loading file 'skin_second_infobar.xml': [Errno 2] No such file or directory: 'skin_second_infobar.xml'
[SKIN] addSkin: skin_subtitles.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
[SKIN] addSkin: skin_display.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_display.xml' added successfully.
[SKIN] addSkin: Satdreamgr-HD-TranspBA/skin.xml scope 12
[Skin] Skin '/usr/share/enigma2/Satdreamgr-HD-TranspBA/skin.xml' added successfully.
[SKIN] addSkin: skin_default.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_default.xml' added successfully.
```

![1_0_1_28_2_212C_EEEE0000_0_0_0_20191229201850](https://user-images.githubusercontent.com/2682247/71560922-63618900-2a78-11ea-9d3a-5ec74c8a7e41.jpg)


Here are the changes to show above debug (and emergency skin disabled).

```
--- /usr/lib/enigma2/python/skin.py.orig
+++ /usr/lib/enigma2/python/skin.py
@@ -81,6 +81,7 @@
        return None

 def addSkin(name, scope=SCOPE_CURRENT_SKIN):
+       print "[SKIN] addSkin: %s scope %s" % (name, scope)
        global domSkins
        filename = resolveFilename(scope, name)
        try:
@@ -152,7 +153,7 @@
 # Add the emergency skin.  This skin should provide enough functionality
 # to enable basic GUI functions to work.
 if config.skin.primary_skin.value != EMERGENCY_SKIN:
-       addSkin(EMERGENCY_SKIN, scope=SCOPE_CURRENT_SKIN)
+       #addSkin(EMERGENCY_SKIN, scope=SCOPE_CURRENT_SKIN)
        addSkin("skin_default.xml", scope=SCOPE_CURRENT_SKIN)

 # Remove global working variables.
```

2019-12-29 20:00 UTC, 68foxboris commented
Satdreamgr-HD-TranspBA install and work,Satdreamgr-HD not start
`[SKIN] addSkin: skin_user.xml scope 12
[Skin] ERROR loading file 'skin_user.xml': [Errno 2] No such file or directory: 'skin_user.xml'
[SKIN] addSkin: skin_box.xml scope 12
[Skin] ERROR loading file 'skin_box.xml': [Errno 2] No such file or directory: 'skin_box.xml'
[SKIN] addSkin: skin_second_infobar.xml scope 12
[Skin] ERROR loading file 'skin_second_infobar.xml': [Errno 2] No such file or directory: 'skin_second_infobar.xml'
[SKIN] addSkin: skin_subtitles.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
[SKIN] addSkin: skin_display.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_display.xml' added successfully.
[SKIN] addSkin: Satdreamgr-HD/skin.xml scope 12
[Skin] Skin '/usr/share/enigma2/Satdreamgr-HD/skin.xml' added successfully.
[SKIN] addSkin: skin_default.xml scope 12
[Skin] Skin '/usr/share/enigma2/skin_default.xml' added successfully.
[FONT] adding font /usr/share/fonts/nmsbd.ttf -> Regular
[FONT] adding font /usr/share/fonts/andale.ttf -> Fixed
[FONT] adding font /usr/share/fonts/tuxtxt.ttf -> Console
[FONT] adding font /usr/share/fonts/DejaVuSans.ttf -> DejaVuSans
[FONT] adding font /usr/share/fonts/ae_AlMateen.ttf -> Replacement
[FONT] adding font Satdreamgr-HD/fonts/UbuntuL.ttf[FONT] failed: No such file or directory
`

2019-12-29 21:39 UTC, athoik commented
It seems like there is an issue loading font!

2019-12-29 23:50 UTC, nautilus7 commented
Yep, loading font's from plugins is buggy. For example, when enigma2 starts, I see this in the log:

```
[FONT] adding font /usr/lib/enigma2/python/Plugins/Extensions/SDGRadio/fonts/mssdr-digitali.ttf -> Digital
```

but when I actually open the plugin I get:

```
[Skin] Error: Font 'Digital' (in 'Digital;100') is not defined!  Using 'Body' font ('Regular') instead.
```

2019-12-30 02:46 UTC, IanSav commented
@68foxboris, can I please see a copy of the skin XML files.  It looks like you have a font tag without a closing tag.

If you can please give my the skin XML files and a matching log file I will have a look at the issue for you.

By the way, while this pull request has not been merged no-one in OpenPLi is using the latest version of the code!  ;)

2019-12-30 02:50 UTC, IanSav commented
@athoik, the emergency skin must always be loaded as one can never know when a user selected skin might be missing a crucial system screen.

The idea is the the emergency skin is loaded first and then the user selected skin is loaded.  Every screen in the user selected skin replaces the equivalent screen in the emergency skin.  If there are any critical screens not in the user skin then the emergency skin will take up the slack.

2019-12-30 02:51 UTC, IanSav commented
I would like to ask that this commit please be merged and all users please retry and tests that resulted in problems.  If any problems persist then please report them again.  Remember to include the logs and, if appropriate, a copy of or pointer to the skin in use.

2019-12-30 06:10 UTC, 68foxboris commented
For example this
[skin.zip](https://github.com/OpenPLi/enigma2/files/4009066/skin.zip)

2019-12-30 07:08 UTC, persianpros commented
The best thign you could do for your skin is:

- Use standard /usr/share/enigma2/fonts/ folder
- Create a bitbake recipe for your extra fonts
- Add the font recipe as RDEPENDS to your skin's bitbake file
- Edit skin.xml and be like standard fonts (filename="lcd.ttf")

2019-12-30 08:48 UTC, IanSav commented
@68foxboris, The copyright block in the skin is a new one on me.  :)

What is the "scale" attribute in a parameter tag meant to be doing?  It isn't decoded!

On to the location issues.  Am I correct in saying that this skin is located as "/usr/share/enigma2/BlackMoonFHD/"?  If so your relative paths are not the best.  For example, when looking for a font that is in "/usr/share/enigma2/BlackMoonFHD/fonts/" then the skin definition should be "<font filename="fonts/regular.ttf" name="Regular" replacement="0" scale="100" />".  This will look for the font in:
1. "/etc/enigma2/fonts/fonts/regular.ttf"
2. "/etc/enigma2/BlackMoonFHD/fonts/regular.ttf"
3. "/etc/enigma2/skin_common/fonts/regular.ttf"
4. "/etc/enigma2/fonts/regular.ttf"  (Not a preferred location!)
5. "/usr/share/enigma2/BlackMoonFHD/fonts/regular.ttf"
6. "/usr/share/enigma2/skin_default/fonts/regular.ttf"
7. "/usr/share/fonts/regular.ttf"
The first font file found will be used and the search terminated.

Have a look at the code in Tools/Directories.py to see how each of the scopes is resolved.

Similarly for all your images don't specify the skin name as the start of the relative path.  Assume that the skin name is part of the seach algorithm so just specifi the image path relative to the skin.  With this arrangement users can allow for sin overrides in the appropriate /etc/enigma2/... area.  I will leave you to look at Directories.py to see how the SCOPE_CURRENT_SKIN files are found.

Does this help explain the problem?  If you don't understand this message and/or require more assistance please let me know.

2019-12-30 09:00 UTC, 68foxboris commented
Unfortunately, I do not make skins, I only collect the image for myself and friends. I install skins. And there are skins in which you can’t change anything.

2019-12-30 09:34 UTC, IanSav commented
Persian Prince and I were going through all the OpenPLi code and skins fixing these issues when another user decided that I didn't know what I was doing and reverted most of the fixes.  The arguments are still raging on the forum.  I have decided to no longer participate in the argument.

Under different circumstances I would have jumped in and fixed the skin for you.  Unfortunately that is not currently an option.  :(

I notice that Persian Prince has responded on this topic.  I would welcome his thoughts about this mess.

2019-12-30 09:38 UTC, IanSav commented
It looks like BlackMoonFHD is from a Russian author.  I don't speak Russian.

I could fix the skin for you to use but that is only a short term patch.  It won't last.

2019-12-30 10:01 UTC, 68foxboris commented
When I remove the hard link to the font folder the skin loads.Now the authors of the skins need to make edits.
`[Skin] Warning: Skin 'skin_user.xml' does not exist!
[Skin] Skin '/usr/share/enigma2/BlackMoonFHD/skin.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_display.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_default.xml' added successfully.
[FONT] adding font /usr/share/fonts/nmsbd.ttf -> Regular
[FONT] adding font /usr/share/fonts/andale.ttf -> Fixed
[FONT] adding font /usr/share/fonts/tuxtxt.ttf -> Console
[FONT] adding font /usr/share/fonts/DejaVuSans.ttf -> DejaVuSans
[FONT] adding font /usr/share/fonts/ae_AlMateen.ttf -> Replacement
[FONT] adding font /usr/share/fonts/LiberationSans-Regular.ttf -> Subs
[FONT] adding font /usr/share/fonts/LiberationSans-Italic.ttf -> Subsi
[FONT] adding font /usr/share/fonts/LiberationSans-Bold.ttf -> Subsb
[FONT] adding font /usr/share/fonts/LiberationSans-BoldItalic.ttf -> Subsz
[Skin] Loading included file '/usr/share/enigma2/BlackMoonFHD/skin_menu.xml'.
[FONT] adding font /usr/share/enigma2/BlackMoonFHD/fonts/regular.ttf -> Regular
[FONT] adding font /usr/share/fonts/md_khmurabi_10.ttf -> Thin
[FONT] adding font /usr/share/enigma2/BlackMoonFHD/fonts/regular.ttf -> Replacement
[FONT] adding font /usr/share/fonts/tuxtxt.ttf -> Console
`

2019-12-30 10:23 UTC, IanSav commented
I'm glad you got it working and sorry it was not easier.

If you communicate with the authors please ask them to review the new Skin.py and Directories.py code to see how the new features may improve or affect their skin development.

If they speak English and would like my assistance please get them to contact me.

2019-12-30 11:31 UTC, athoik commented
@iansav,

Please point me the code where skin.xml (emergency skin) was loaded before your changes?

2019-12-30 11:59 UTC, IanSav commented
> Please point me the code where skin.xml (emergency skin) was loaded before your changes?

Do you mean in Skin.py before the refactor?

2019-12-30 12:00 UTC, nautilus7 commented
Yes, that's what he means.

2019-12-30 12:08 UTC, IanSav commented
https://github.com/OpenPLi/enigma2/blob/68e7e9c9601c6428bf6e3f9faa9fc6257df199fd/skin.py#L119

2019-12-30 12:33 UTC, nautilus7 commented
If the "skin_defaul.xml" was the "emergency" skin, then why now we do this: https://github.com/OpenPLi/enigma2/blob/develop/skin.py#L18

2019-12-30 12:38 UTC, IanSav commented
Both are required to be a complete skin.

For OpenViX I have reworked the emergency skin to be a combination of both parts.  This goes in combination with my refactored SkinSelector.py.  For OpenPLi I didn't want to change too much in one hit.  That doesn't seem to go down well with some people.

2019-12-30 14:53 UTC, athoik commented
Skin.xml previously wasn't loaded. Now it is.

OpenVix is reworked?

Why last change is before 4 months.

I suggest next time to create a feature branch with all the changes you like.

Now develop branch is broken again (both skin and fonts).

And we don't understand in top of that?

2019-12-30 15:49 UTC, persianpros commented
@IanSav 

PLi is using "SkinSelector" as a plugin while we (Vision) and ViX also ATV are using SkinSelector.py as a "Screen".

That's why our code is improved and we need to do it for PLi if they're ok with it.

Regarding fonts almost all skins are ruining enigma2 standards which is:

 /usr/share/fonts/

I just introduced "enigma2-plugin-fonts" today: https://github.com/OpenVisionE2/openvision-oe/commit/0394a79dd5b4d72f771801c27532a7d6aef3831a

plus its repository: https://github.com/OpenVisionE2/enigma2-fonts

You're welcome to use our repo and even participate in it with making skins standard again, fonts should not load from any other path and they must be available for all.

Why should we add a font somewhere else and don't let other skins to use it? This is ridiculously stupid.

All skin recipes should RDEPENDS on the needed fonts not provide them.

If OE-A or anyone else wants access to our font repo just let me know.

2019-12-30 16:08 UTC, WanWizard commented
A lot of this misery comes from plugins hardcoding stuff they shouldn't, whether it be due to ignorance, differences between Enigma versions, or something else.

In no other "windowed" environment is "user" code allowed to deal with GUI construction. The code calls the Window manager library to paint a dialog, which is does with the elements provided by the active "skin".

This problem will only go away when we add those library functions to Enigma, and ban the use of skins, skin elements, and hardcoded skin stuff in plugins. It will also make sure plugin screens have the look-and-feel of the active skin, and not of the emergency skin that happens to be in the image...

2019-12-30 20:01 UTC, IanSav commented
@athoik, Yes OpenViX have identical changes in the Experimental branch.  The testing has been going so well it should soon be promoted to Dev and then production.

I wish people would tell me what is broken and provide the logs I requested rather than say it is broken and shouldn't have been submitted.  As people should well know by now I develop and test my code as best I can before submitting it.  If I am told about a problem I work 24 hours a day to fix it.  The point of committing the code to a Develop branch is so that it can be tested by developers.  My expectation is that developers would be supportive of testing to ensure that any code contribution is the best that it can be.

You tell me that the Develop branch is broken but you provide absolutely no information on what is broken so that I can have a chance to address the problem.

If you don't understand something I have done why don't you ask me to explain it?  If you don't understand the explanation then tell me so I can try to explain it in a different way.

2019-12-30 20:11 UTC, IanSav commented
@persianpros, I disagree with you about the management of fonts.  In my OverlayHD skin I provide all the fonts I use within the skin.  That is the only way I can be sure that every font I use will be available to the skin.

Placing fonts into "/usr/share/fonts/" is a fine idea, in theory, but unless your skin package owns the font then you have no real guarantee that the font you want or expect will be present.  Further, as the fonts are independently managed by other packages the fonts can come or go independently.  Also, because the fonts are controlled by another package you shouldn't/mustn't play with them via a different package.  As I understand the package manager every file can only have one owner.

The reason I haven't yet brought the new SkinSelector to OpenPLi is because it is still undergoing tests on OpenViX.  Also the SkinSelector has full management control of both GUI and display skins.  Optional display skins are not a feature yet used by OpenPLi.  I didn't want to introduce too much change at once.

2019-12-30 20:20 UTC, IanSav commented
@WanWizard, believe it or not all my code and changes were designed to maintain backward compatibility wherever possible.  If I need to change something I usually always declare the changed behavior.  If things have been broken then it is completely unintentional.

I can only address problems if people tell me what the problems are.  I have repeatedly asked people that if there is a problems please describe the problem and provide me with a log file and I will correct the issue.  To date very few people have provided me with information about the perceived problems and even fewer have provided logs.  For all the people who have provided me the information I have either explained the problem or corrected the code.

This pull request contains fixes and improvements for the code but here it sits awaiting a merge.  In the meantime people continue to complain about issues.  Are the issues new or are they already fixed in this update.  I don't know because I am not getting proper bug reports on which I can act.

I appreciate your comments about the poor state of Enigma2.  As you know I have been trying to improve things for all images.  Persian Prince was a massive help in the effort to improve and fix things  The task has been severely compromised by the interference of others.  I can't help if the work is sabotaged.  :(

2019-12-30 20:37 UTC, athoik commented
I am sure I did mention above, what is going wrong with skin.xml including screeshots. Also nautilus7 is trying to explain the issue introduce font with loading.

Here is one skin affected https://github.com/satdreamgr/Satdreamgr-HD-TranspBA

Here is one plugin affected with loading font not working any more https://github.com/satdreamgr/SDGRadio

Skin owners should know what to change, should know what is obsolete.

What log should we place for a skin not working anymore? Obviously there is no crash.

What log to get for a font not working anymore. Obviously there is no crash.

2019-12-30 20:39 UTC, IanSav commented
By the way, the reason I include "skin.xml" as well as "skin_default.xml" as the emergency skin is because of some history, of which I know nothing about, the emergency skin appears to have been split into two parts.  On OpenPLi the split seems different but I assumed that both parts are needed.  Perhaps this may not be the case.  In my testing I did not fault the code I submitted.  That doesn't mean it was correct.  If I should not be using the "skin.xml" part, or the "skin_default.xml" part, them please offer this as a bug report.  It would be a very fast fix to change the load sequence if I have this wrong.

If people will work with me, rather than against me, all things can be fixed without all this angst.

2019-12-30 20:39 UTC, nautilus7 commented
@IanSav I mentioned a problem with using fonts loaded from a plugin. Good practice or not I don't care, but this was working before... I also attached logs, but you may have missed them:

At enigma2 start, I can see the font at the plugin code, is loading ok: 
```
[FONT] adding font /usr/lib/enigma2/python/Plugins/Extensions/SDGRadio/fonts/mssdr-digitali.ttf -> Digital
```

but when I actually open the plugin I get:

```
[Skin] Error: Font 'Digital' (in 'Digital;100') is not defined!  Using 'Body' font ('Regular') instead.
```
Isn't it enough to show that something is wrong?

2019-12-30 20:42 UTC, IanSav commented
Hi @athoik, a standard debug level 4 log is all I need.

I accept you were trying to alert me to a problem but I did not recognise it as a problem.  I am starting to understand that on OpenPLi there is something wrong or out of place with the provided "skin.xml".  How can I provide a modified "Skin.py" for people to test with the "skin.xml" for the emergency skin changes to "skin_default.xml"?

2019-12-30 20:45 UTC, IanSav commented
@nautilus7, no that is not enough information.  There will be more to be learned from other parts of the debug log.  I need context of the error.

2019-12-30 21:05 UTC, IanSav commented
If you want to edit your own copy of "Skin.py" to test the "skin.xml" theory please make the following changes:
Change the code on line 18 from:
`EMERGENCY_SKIN = "/usr/share/enigma2/skin.xml"`
to:
`EMERGENCY_SKIN = "skin_default.xml"`

Then change the code on lines 155-156 from:
`if config.skin.primary_skin.value != EMERGENCY_SKIN:
	addSkin(EMERGENCY_SKIN, scope=SCOPE_CURRENT_SKIN)
	addSkin("skin_default.xml", scope=SCOPE_CURRENT_SKIN)`
to:
`if config.skin.primary_skin.value != EMERGENCY_SKIN:
	addSkin(EMERGENCY_SKIN, scope=SCOPE_CURRENT_SKIN)`

Then retest the code for the problems you are reporting.

Please note that I need you to use the version of Skin.py as it is in THIS pull request.  There are fixes to the code that may impact this issue!

Edit: Sorry but the code quoting appears to be broken at the moment.  Please be careful making the changes suggested above.  They look correct in the edit screen but are wrong in the preview screen!

2019-12-30 21:08 UTC, nautilus7 commented
@IanSav here is the debug log showing plugin font not usable...

**image:** satdreamgr

**skin:** TranspBA-FHDmod (not public) - but it does not have a specific screen for that plugin, it uses the embedded skin in the plugin!

**plugin:** sdgradio from here https://github.com/satdreamgr/SDGRadio

```
root@osmio4k:~#
root@osmio4k:~#
root@osmio4k:~#
root@osmio4k:~# ENIGMA_DEBUG_LVL=4 enigma2
PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 10
ENIGMA_DEBUG_LVL=4
[Avahi] avahi_timeout_new
[Avahi] avahi_watch_new(3 0x1)
[Avahi] avahi_timeout_update
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] client state: 2
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[eInit] + (1) Background File Eraser
[eInit] + (5) Tuxtxt
[eInit] + (8) graphics acceleration manager
[eInit] + (9) Font Render Class
[FONT] initializing lib...
[FONT] loading fonts...
[FONT] Intializing font cache, using max. 4MB...
[eInit] + (9) gLCD
[eFbLCD] /dev/fb1: No such file or directory
[eFbLCD] framebuffer /dev/fb1 not available
[eDboxLCD] xres=132, yres=64, bpp=8 lcd_type=2
[eLCD] (132x64x8) buffer 0x8b3180 8448 bytes, stride 132
[gLCDDC] resolution: 132x64x8 stride=132
[eInit] + (9) GFBDC
[fb] /dev/fb0: 24300k video mem
[fb] double buffering available!
[gFBDC] resolution: 1920x1080x32 stride=7680, 8100kB available for acceleration surfaces.
[eInit] + (10) gRC
[gRC] thread created successfully
[eInit] + (15) eWindowStyleManager
[eInit] + (20) AVSwitch Driver
[eAVSwitch] failed to open /dev/dbox/fp0 to monitor vcr scart slow blanking changed: No such file or directory
[eInit] + (20) misc options
[eInit] + (20) RC Input layer
[eInit] + (20) UHF Modulator
[eRFmod] couldnt open /dev/rfmod0: No such file or directory
[eInit] + (20) DVB-CI UI
[eInit] + (21) input device driver
[eInputDeviceInit] adding device /dev/input/event0
[eRCInputEventDriver] devicename=dreambox advanced remote control (native)
[eRCInputEventDriver] devicename=dreambox advanced remote control (native)
[eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
[eInputDeviceInit] adding device /dev/input/event1
[eRCInputEventDriver] devicename=dreambox ir mouse
[eRCInputEventDriver] devicename=dreambox ir mouse
[eRCDeviceInputDev] device "dreambox ir mouse" is a mouse
[eInputDeviceInit] adding device /dev/input/event2
[eRCInputEventDriver] devicename=dreambox front panel
[eRCInputEventDriver] devicename=dreambox front panel
[eRCDeviceInputDev] device "dreambox front panel" is a remotecontrol
[eInputDeviceInit] Found 3 input devices.
[eInit] + (22) Hdmi CEC driver
[eInit] + (30) eActionMap
[eInit] + (35) CA handler
[eInit] + (35) CI Slots
[CI] scanning for common interfaces..
[CI] done, found 0 common interface slots
[eInit] + (40) eServiceCenter
[eServiceCenter] settings instance.
[eInit] + (41) Stream server
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] avahi_timeout_new
[Avahi] avahi_timeout_free
[Avahi] Registered osmio4k (_e2stream._tcp) on osmio4k:8001
[eInit] + (41) RTSP Stream server
[eInit] + (41) Encoders
[eInit] + (41) eServiceFactoryDVB
[eInit] + (41) eServiceFactoryFS
[eInit] + (41) eServiceFactoryM2TS
[eInit] + (41) eServiceFactoryHDMI
[eInit] + (41) eServiceFactoryTS
[eInit] + (41) eServiceFactoryWebTS
[eInit] + (41) eServiceFactoryDVD
[eInit] reached rl 70
[eDVBDB] ---- opening lame channel db
[eDVBDB] reading services (version 4)
[eDVBDB] loaded 1099 channels/transponders and 11711 services
eDVBSatelliteEquipmentControl::clear()
[eDVBResourceManager] scanning for frontends..
[eDVBFrontend0] opening frontend
[eDVBFrontend0] opening frontend
[eDVBFrontend0] frontend 0 has DVB API 50b
[eDVBFrontend0] close frontend
[eDVBFrontend1] opening frontend
[eDVBFrontend1] opening frontend
[eDVBFrontend1] frontend 1 has DVB API 50b
[eDVBFrontend1] close frontend
[eDVBAdapterLinux] get demux 0
[eDVBAdapterLinux] get demux 1
[eDVBAdapterLinux] get demux 2
[eDVBAdapterLinux] get demux 3
[eDVBAdapterLinux] get demux 4
[eDVBAdapterLinux] get demux 5
[eDVBAdapterLinux] get demux 6
[eDVBAdapterLinux] get demux 7
[eDVBAdapterLinux] get demux 8
[eDVBAdapterLinux] get demux 9
[eDVBAdapterLinux] get demux 10
[eDVBAdapterLinux] get demux 11
[eDVBAdapterLinux] get demux 12
[eDVBAdapterLinux] get demux 13
[eDVBAdapterLinux] get demux 14
[eDVBAdapterLinux] get demux 15
[eDVBResourceManager] found 1 adapter, 2 frontends(2 sim) and 16 demux
[eDVBLocalTimeHandler] Use valid Linux Time :) (RTC?)
[eEPGCache] Initialized EPGCache (wait for setCacheFile call now)
[MAIN] Loading spinners...
[MAIN] found 10 spinner!
[MAIN] executing main
[setIoPrio] best-effort level 3 ok
[HardwareInfo] Scanning hardware info
Detected: osmio4k (0-20191202)
[eDVBFrontend] Failed to open /dev/dbox/fp0
[Misc_Options] 12Vdetect cannot open /proc/stb/misc/12V_output: No such file or directory
[Harddisk] enumerating block devices...
[Harddisk] new device sda -> /dev/sda -> /dev/sda
[RTC] set RTC offset to 7200 sec.
Activating keymap: Default (US)
[Console] command: loadkmap < /usr/share/keymaps/default.kmap
[eConsoleAppContainer] Starting /bin/sh
Activating language
[Skin] ERROR loading file 'skin_user.xml': [Errno 2] No such file or directory: 'skin_user.xml'
[Skin] ERROR loading file 'skin_box.xml': [Errno 2] No such file or directory: 'skin_box.xml'
[Skin] ERROR loading file 'skin_second_infobar.xml': [Errno 2] No such file or directory: 'skin_second_infobar.xml'
[Skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_display.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/TranspBA-FHDmod/skin.xml' added successfully.
[Skin] Skin '/usr/share/enigma2/skin_default.xml' added successfully.
[NimManager] Reading satellites.xml
[NimManager] Reading cables.xml
[NimManager] Reading terrestrial.xml
[InitNimManager] enable combined tuner type(s) DVB-T2
eDVBSatelliteEquipmentControl::clear()
[SecConfigure] sec config cleared
[eDVBFrontend] setSlotInfo for dvb frontend 0 to slotid 0, descr Availink AVL6261, need rotorworkaround No, enabled Yes, DVB-S2 Yes
[eDVBFrontend] setSlotInfo for dvb frontend 1 to slotid 1, descr Availink AVL6762, need rotorworkaround No, enabled Yes, DVB-S2 No
[SecConfigure] slot: 0 configmode: advanced
[eDVBSatelliteEquipmentControl::setSlotNotLinked] slot=0
[SecConfigure] add 19 to 1
[SecConfigure] add 30 to 1
[SecConfigure] add 48 to 1
[SecConfigure] add 70 to 1
[SecConfigure] add 90 to 1
[SecConfigure] add 100 to 1
[SecConfigure] add 130 to 1
[SecConfigure] add 160 to 1
[SecConfigure] add 192 to 1
[SecConfigure] add 216 to 1
[SecConfigure] add 235 to 1
[SecConfigure] add 390 to 1
[SecConfigure] add 420 to 1
[SecConfigure] add 3300 to 1
[SecConfigure] add 3325 to 1
[SecConfigure] add 3355 to 1
[SecConfigure] add 3380 to 1
[SecConfigure] add 3400 to 1
[SecConfigure] add 3420 to 1
[SecConfigure] add 3450 to 1
[SecConfigure] add 3460 to 1
[SecConfigure] add 3490 to 1
[SecConfigure] add 3520 to 1
[SecConfigure] add 3530 to 1
[SecConfigure] add 3550 to 1
[SecConfigure] add 3560 to 1
[SecConfigure] add 3570 to 1
[SecConfigure] add 3592 to 1
[eDVBSatelliteEquipmentControl::addLNB] lnb=0)
[eDVBSatelliteEquipmentControl::setLNBNum] lnbnum=1
eDVBSatelliteEquipmentControl::setLNBSatCRformat(0)
[eDVBSatelliteEquipmentControl::setLNBLOFL] logfl=9750000
[eDVBSatelliteEquipmentControl::setLNBLOFH] lofh=10600000
[eDVBSatelliteEquipmentControl::setLNBThreshold] threshold=11700000
[eDVBSatelliteEquipmentControl::setLNBIncreasedVoltage] onoff=0
[eDVBSatelliteEquipmentControl::setDiSEqcMode] mode=3
[eD [...]

2019-12-30 21:26 UTC, IanSav commented
@nautilus7,
The skin load sequence looks okay.
The skin parse sequence looks okay.
What is producing this:
`[getFonts] fontDir: /usr/share/fonts/
[getFonts] find font Regular in skin_default.xml
[getFonts] find font Fixed in skin_default.xml
[getFonts] find font Console in skin_default.xml
[getFonts] find font DejaVuSans in skin_default.xml
[getFonts] find font Replacement in skin_default.xml
[getFonts] find font Subs in skin_subtitles.xml
[getFonts] find font Subsi in skin_subtitles.xml
[getFonts] find font Subsb in skin_subtitles.xml
[getFonts] find font Subsz in skin_subtitles.xml`

What is loading the "Digital" font?  It does not appear to be coming from any of the skins?  It looks like the global fonts dictionary is not being updated when that font is being loaded.

2019-12-30 21:34 UTC, athoik commented
For GitHub markdown cheat sheet see here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

Plugin is loading font using enigma2 addFont API call. See https://github.com/satdreamgr/SDGRadio/blob/a9b1586046dbdf8f3b611d80b02c932781127988/plugin/plugin.py#L49

2019-12-30 21:37 UTC, IanSav commented
Hi @athoik, let me look at weakening the font validation code to allow for this situation to be accepted.  Obviously it would be better if all fonts added to Enigma2 were registered in the master font dictionary.  That is what all the skin loads do.

2019-12-30 21:41 UTC, IanSav commented
Thanks for the markdown hint.  The button in the GUI interface is broken!  :(

2019-12-30 21:44 UTC, nautilus7 commented
@IanSav, just let us know HOW we should add a font from a plugin, to the global fonts dict, in the revised code. We don't have any problem changing our code.

2019-12-30 21:49 UTC, IanSav commented
@nautilus7, I think it would be better if I offer you a new API in the skin code to add the font.  That way all the internal database manipulations can be done for you and you won't need to play with internal skin structures.  Would that be acceptable to you?

2019-12-30 21:52 UTC, IanSav commented
By the way, I just checked the old and new Skin.py code.  While I report the font error I actually pass the font request through to the font renderer.  This is what was done before.  All I added is the error message to tell people that the font is not correctly defined.

2019-12-30 21:56 UTC, nautilus7 commented
> @nautilus7, I think it would be better if I offer you a new API in the skin code to add the font. That way all the internal database manipulations can be done for you and you won't need to play with internal skin structures. Would that be acceptable to you?

Not, a problem at all. As far as I know what I should change to adapt to the new code, I don't have any issue.

2019-12-30 21:58 UTC, IanSav commented
@nautilus7, actually there is a way you can add the font properly yourself with the latest Skin.py change!

In the commit notes above I have added a way for plugins that use the updated "loadSkin()" method to also load core elements like fonts.  That means you should be able to add a "\<fonts\>" block to your internal skin and the skin loader should make the adjustments for you.  Would you like to try that or would you prefer a new API?

2019-12-30 22:05 UTC, nautilus7 commented
If I add the font into the skin embedded to the plugin (internal  as you say), then the font will be restricted to that skin only. The way it was before, the font was available to other skins/plugins as well.

So, I guess a new api (with same parameters) will be better.

2019-12-30 22:11 UTC, IanSav commented
@nautilus7, no the addition should be added to the system lists and dictionaries so it should become global.  Anyway I have already coded an API interface as well.  ;)

'''def addSkinFont(filename, name="Regular", size=20, height=25, width=18, scale=100, isReplacement=False, render=0):'''

Would this be sufficient for your needs?

2019-12-30 22:14 UTC, nautilus7 commented
I suppose the parameters size, height, width, scale, etc will not be mandatory, right? Otherwise it is more than enough.

2019-12-30 22:15 UTC, athoik commented
But what will happen to plugins still using enigma2 addFont?

Why addFont doesn't work any more? 
Or what is changed in skin.py that doesn't property check enigma2 font cache any more?

2019-12-30 22:17 UTC, IanSav commented
Correct, only the font filename and name need to be provided though I do have a default for the name which I think I should remove.  Redefining "Regular" by accident would not be good!  ;)  The font filename is processed by SCOPE_FONTS so if the font is actually is a standard font location you only need provide the appropriate relative path.

2019-12-30 22:21 UTC, IanSav commented
@athoik, "addFont()" is working as it always was.  The problem is that this is a raw C++ layer enigma2 call.  It does not update the higher level Python layer lists and dictionaries the skins use for validation.

People using "addFont()" should have checked how it was used in Skin.py and they would have noted the tables that were not being updated.

Please note that I have enhanced the data structures in Skin.py in my refactor to improve the validation of the fonts being used.  As noted in a post above, above, even though the skin now reports an error the font is still passed to the enigma2 C++ layer for processing.

2019-12-30 22:23 UTC, IanSav commented
This is the updated API call.  Now both the filename and the font name are required arguments.

```
def addSkinFont(filename, name, size=20, height=25, width=18, scale=100, isReplacement=False, render=0):
	filename = resolveFilename(SCOPE_FONTS, filename, path_prefix=pathSkin)
	addFont(filename, name, scale, isReplacement, render)
	fontNames.append(name)
	fonts[name] = (name, size, height, width)
	# print "[Skin] Add font: Font path='%s', name='%s', scale=%d, isReplacement=%s, render=%d." % (filename, name, scale, isReplacement, render)
```

Would you like this pull request updated with this API or is there anything else you would like changed?

2019-12-30 22:31 UTC, nautilus7 commented
Sorry, but it seems I didn't understand you before... I only want the font to be available as a font "name" so the skins can select their own size, not as font "alias" which already defines a size.

Before, by putting this in a plugin, 


```
addFont(resolveFilename(SCOPE_PLUGINS, "Extensions/SDGRadio/fonts/mssdr-digitali.ttf"), "Digital", 90, 1)

```

I could do this in my third party skin:

```
<widget name="freq" position="320,200" size="790,90" valign="center" halign="center" font="Digital;100" zPosition="5" transparent="1" foregroundColor="#ff1100" backgroundColor="#ff1100"/>

```

and use the font with my own size.

2019-12-30 23:14 UTC, IanSav commented
@nautilus7, the "parseFont()" method accepts a size and overrides the size in the alias table.

2019-12-30 23:20 UTC, nautilus7 commented
I am very tired as well and I cannot  think right now... Will something like this 

```
    <widget name="freq" position="320,200" size="790,90" font="Digital;100" foregroundColor="#ff1100"/>
```

where "Digital" is a font defined in a plugin, be possible?

2019-12-31 00:19 UTC, AbuBaniaz commented
> 
> 
> Persian Prince and I were going through all the OpenPLi code and skins fixing these issues when another user decided that I didn't know what I was doing and reverted most of the fixes. The arguments are still raging on the forum. I have decided to no longer participate in the argument.
> 
> Under different circumstances I would have jumped in and fixed the skin for you. Unfortunately that is not currently an option. :(
> 
> I notice that Persian Prince has responded on this topic. I would welcome his thoughts about this mess.

And the changes you made broke plugins.

2019-12-31 00:23 UTC, AbuBaniaz commented
The same thing happens on Huevos's image. You cannot change skins unless you manually add a  new "emergency skin". I no longer use his image as I cannot be arsed with transferring files to make an image work.

This is probably caused by the fact that "emergency skin" was called "default_skin" and somewhere wires are crossed.

2019-12-31 00:25 UTC, AbuBaniaz commented
> 
> 
> @athoik, Yes OpenViX have identical changes in the Experimental branch. The testing has been going so well it should soon be promoted to Dev and then production.
> 
> I wish people would tell me what is broken and provide the logs I requested rather than say it is broken and shouldn't have been submitted. As people should well know by now I develop and test my code as best I can before submitting it. If I am told about a problem I work 24 hours a day to fix it. The point of committing the code to a Develop branch is so that it can be tested by developers. My expectation is that developers would be supportive of testing to ensure that any code contribution is the best that it can be.
> 
> You tell me that the Develop branch is broken but you provide absolutely no information on what is broken so that I can have a chance to address the problem.
> 
> If you don't understand something I have done why don't you ask me to explain it? If you don't understand the explanation then tell me so I can try to explain it in a different way.

There is no experimental branch on Vix

2019-12-31 00:31 UTC, AbuBaniaz commented
> 
> 
> Persian Prince and I were going through all the OpenPLi code and skins fixing these issues when another user decided that I didn't know what I was doing and reverted most of the fixes. The arguments are still raging on the forum. I have decided to no longer participate in the argument.
> 
> Under different circumstances I would have jumped in and fixed the skin for you. Unfortunately that is not currently an option. :(
> 
> I notice that Persian Prince has responded on this topic. I would welcome his thoughts about this mess.

The changes you made were in embedded skins within plugins. Not actual skins.

Anyway, the three of you can call embedded skins hacks as much as you want. You are entitled to your opinion.

2019-12-31 00:39 UTC, IanSav commented
@nautilus7, absolutely.  Contrary to the noise being injected here, nothing has changed with the code and skin functionality.  All you encountered was a new error report because the way you added the font was unknown to the skin engine.

This has always been an error that was never properly reported.

2019-12-31 00:41 UTC, IanSav commented
The new API is written but I am too tired to test it myself at the moment.  Would anyone like the code to test?

2019-12-31 00:48 UTC, nautilus7 commented
> @nautilus7, absolutely. Contrary to the noise being injected here, nothing has changed with the code and skin functionality. All you encountered was a new error report because the way you added the font was unknown to the skin engine.
> 
> This has always been an error that was never properly reported.

This being just an new error report for an old unreported error does NOT explain why it worked before and now it doesn't.

Can you post the code for testing? Here or in a gist or wherever you like. I will test tomorrow.

2019-12-31 00:55 UTC, IanSav commented
> This being just an new error report for an old unreported error does NOT explain why it worked before and now it doesn't.

This is the bit I am trying to understand.  I traced the code path and even though the error is reported I still pass the requested font to the "gFont()" call.

> Can you post the code for testing? Here or in a gist or wherever you like. I will test tomorrow.

I really need for the other fixes in this pull request to be merged and tested to see if some of these issues are already fixed.

I am going to break one of my rules and commit this code without testing it myself.  Given it is an API it won't be used unless it is called.  We can both test the new API when we get some sleep and are refreshed.  If you find any issues please contact me and I will address any concerns as quickly as I can.

2019-12-31 10:12 UTC, athoik commented
The  commit fa3a83d seems fine. 

The addSkinFont I am not sure yet. I didn't manage to adapt plugin.

Although I still think that there will be a "gap" between python code and C++. 

Most probably instead of caching enigma2 names in skin.py get them directly from C++.
That way you can fill the "gap" because you will always know the internal state of enigma2.


```
diff --git a/lib/gdi/font.cpp b/lib/gdi/font.cpp
index b4c6b7a..5ff7ad4 100644
--- a/lib/gdi/font.cpp
+++ b/lib/gdi/font.cpp
@@ -275,6 +275,17 @@ int fontRenderClass::getFont(ePtr<Font> &font, const std::string &face, int size
        return 0;
 }

+// get all font faces (names) available in enigma2
+std::vector<std::string> fontRenderClass::getFontFaces()
+{
+       std::vector<std::string> v;
+       for (fontListEntry *f=font; f; f=f->next)
+       {
+               v.push_back(f->face);
+       }
+       return v;
+}
+
 void addFont(const char *filename, const char *alias, int scale_factor, int is_replacement, int renderflags)
 {
        fontRenderClass::getInstance()->AddFont(filename, alias, scale_factor, renderflags);
diff --git a/lib/gdi/font.h b/lib/gdi/font.h
index 0364906..de31cdc 100644
--- a/lib/gdi/font.h
+++ b/lib/gdi/font.h
@@ -77,6 +77,7 @@ public:
        std::string AddFont(const std::string &filename, const std::string &name, int scale, int renderflags = 0);
        FT_Error FTC_Face_Requester(FTC_FaceID  face_id, FT_Face* aface);
        int getFont(ePtr<Font> &font, const std::string &face, int size, int tabwidth=-1);
+       std::vector<std::string> getFontFaces();
        fontRenderClass();
        ~fontRenderClass();
 #endif
diff --git a/lib/python/enigma_python.i b/lib/python/enigma_python.i
index 9a0426d..cfb0e15 100644
--- a/lib/python/enigma_python.i
+++ b/lib/python/enigma_python.i
@@ -423,6 +423,18 @@ int getLinkedSlotID(int fe)
 }
 %}

+PyObject *getFontFaces();
+%{
+PyObject *getFontFaces()
+{
+       std::vector<std::string> v = fontRenderClass::getInstance()->getFontFaces();
+       ePyObject result = PyList_New(v.size());
+       for (size_t i = 0; i < v.size(); i++)
+               PyList_SET_ITEM(result, i, PyString_FromString(v[i].c_str()));
+        return result;
+}
+%}
+
 /************** temp *****************/

        /* need a better place for this, i agree. */
```

2019-12-31 10:52 UTC, IanSav commented
If this code is added to OpenPLi and the other images I would integrate it into the skin processor.

What is the Python interface?

2019-12-31 12:43 UTC, merged

2019-12-31 15:40 UTC, athoik commented
I pushed change here: https://github.com/OpenPLi/enigma2/commit/dae5f9a1a87566cd27c5c2e809c2339fa2dffca1

Python interface? You mean how to export enigma2 internals using swig?

2019-12-31 16:25 UTC, athoik commented
With the following change I get the proper font (just like it was working before).

```
diff --git a/skin.py b/skin.py
index d06d270..476462d 100644
--- a/skin.py
+++ b/skin.py
@@ -4,7 +4,7 @@ import os
 import xml.etree.cElementTree

 profile("LOAD:enigma_skin")
-from enigma import addFont, eLabel, ePixmap, ePoint, eRect, eSize, eWindow, eWindowStyleManager, eWindowStyleSkinned, getDesktop, gFont, gRGB
+from enigma import addFont, eLabel, ePixmap, ePoint, eRect, eSize, eWindow, eWindowStyleManager, eWindowStyleSkinned, getDesktop, getFontFaces, gFont, gRGB
 from Components.config import ConfigSubsection, ConfigText, config
 from Components.RcModel import rc_model
 from Components.Sources.Source import ObsoleteSource
@@ -267,7 +267,7 @@ def parseFont(s, scale=((1, 1), (1, 1))):
                name = f[0]
                size = f[1] if size is None else size
        except KeyError:
-               if name not in fontNames:
+               if name not in getFontFaces():
                        f = fonts["Body"]
                        print "[Skin] Error: Font '%s' (in '%s') is not defined!  Using 'Body' font ('%s') instead." % (name, s, f[0])
                        name = f[0]
```