es.po + lt.po + fr.po
OpenPLi/enigma2 pull request #3122
Opened 2021-09-11 18:13 UTC by pr2git

2021-09-11 22:47 UTC, nautilus7 requested changes

2021-09-11 22:47 UTC, nautilus7 commented on po/es.po
> +msgstr "Conector FBC% s"
Variable %s is malformed.

2021-09-11 22:47 UTC, nautilus7 commented on po/es.po
> +msgstr "Banda de usuario% d (% s)"
Same here... Variables are malformed.

2021-09-11 22:47 UTC, nautilus7 commented on po/es.po
> +msgstr "¡Tienes que esperar %(min)d minutos,% (seg) d segundos!"
Here as well,,, It should be %(sec)d like in original string.

2021-09-11 22:47 UTC, nautilus7 commented on po/es.po
> +msgstr "¡Tienes que esperar %(min)d minutos,% (seg) d segundos!"
Here as well,,, It should be %(sec)d like in original string.

2021-09-11 22:47 UTC, nautilus7 commented on po/fr.po
> +msgstr "Sélectionnez le caractère pour remplacer les retour à  la  ligne dans epg."
Are the double spaces intended here?

2021-09-11 22:47 UTC, nautilus7 commented on po/fr.po
> +msgstr "Vous devez attendre %(min)d minutes, %(sec)d secondes !"
Is the space before the "!" intended?

2021-09-11 22:51 UTC, nautilus7 requested changes

2021-09-11 22:51 UTC, nautilus7 commented on po/es.po
> +msgstr "Banda de usuario% d"
Same here, malformed variable.

2021-09-11 22:51 UTC, nautilus7 commented on po/es.po
> +msgstr "Banda de usuario% d"
Same here, malformed variable.

2021-09-12 07:24 UTC, closed without merging

2021-09-12 07:26 UTC, pr2git commented
The es.po is not mine it is one from angelito thanks for pointing out those errors. Sadly this looks like automatic translation without any check from the creator angelito. I am just creating the PR for him.
I will create another PR just with FR and LT.

2021-09-12 07:43 UTC, nautilus7 commented
Yes, I know these are not all made by you.

Maybe it's easier to re-open the previous PR and just correct the errors by adding another commit, or even amend to the initial commit. Isn't it easier to do it this way?

2021-09-12 07:45 UTC, nautilus7 commented
Or I can fix the es.po and make a PR...